
// INSERT HERE YOUR CUSTOM CONSTANTS




// START CRUD CONSTANTS

// COMPANY
export const RESET_COMPANY = "RESET_COMPANY";
export const CREATE_COMPANY_SUCCESS = "CREATE_COMPANY_SUCCESS";
export const DELETE_COMPANY_SUCCESS = "DELETE_COMPANY_SUCCESS";
export const GET_COMPANY_SUCCESS = "GET_COMPANY_SUCCESS";
export const LIST_COMPANY_SUCCESS = "LIST_COMPANY_SUCCESS";
export const UPDATE_COMPANY_SUCCESS = "UPDATE_COMPANY_SUCCESS";

// SITE
export const RESET_SITE = "RESET_SITE";
export const CREATE_SITE_SUCCESS = "CREATE_SITE_SUCCESS";
export const DELETE_SITE_SUCCESS = "DELETE_SITE_SUCCESS";
export const GET_SITE_SUCCESS = "GET_SITE_SUCCESS";
export const LIST_SITE_SUCCESS = "LIST_SITE_SUCCESS";
export const UPDATE_SITE_SUCCESS = "UPDATE_SITE_SUCCESS";

// USER
export const RESET_USER = "RESET_USER";
export const CHANGEPASSWORD_USER_SUCCESS = "CHANGEPASSWORD_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

// END CRUD CONSTANTS

// USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ADMIN_SUCCESS = "CHANGE_PASSWORD_ADMIN_SUCCESS";
